### ISSUE TITLE
Minifying n3 breaks _encodeIriOrBlank

### ISSUE THREAD

**Issue by peacememories** [rdfjs/N3.js#135]
When minifying n3 with uglify, protoype names get replaced by shorter ones. This breaks the `termType` check in [`_encodeIriOrBlank`](https://github.com/rdfjs/N3.js/blob/master/lib/N3Writer.js#L125) in the Writer.

![image](https://user-images.githubusercontent.com/1326334/39818659-bbee9202-53a1-11e8-864a-fb4c374d3f71.png)

Version: 1.0.0-alpha

**Comment by peacememories** [comment]
A simple fix would probably be to use `NamedNode.name` instead of `'NamedNode'`
Not sure how well this scales though

**Comment by RubenVerborgh** [comment]
uglify should be told not to do this: termType is a required field for the RDF/js specification.

**Comment by RubenVerborgh** [comment]
Ah wait, it's the constructor name. That changes things. I'll check.

**Comment by RubenVerborgh** [comment]
Hmm, this is really unfortunate, but I guess I have no choice but to be compatible with Uglify. Unsure why it would mangle names of exposed constructors.

**Comment by RubenVerborgh** [comment]
> A simple fix would probably be to use NamedNode.name instead of 'NamedNode'

So that wasn't possible, because `termType` is required to be exposed by the RDF.js specification. I'm just adding it as a string now.

**Comment by RubenVerborgh** [comment]
Released as 1.0.0-beta.1

**Comment by peacememories** [comment]
Thanks a lot, this allows us to minify function names again :) (we had to turn that off in the meantime)

**Comment by RubenVerborgh** [comment]
The size after gzipping is now probably worse than without function name mangling, but if it's in the default configuration, we should definitely support it.

**Comment by peacememories** [comment]
Well, for this library maybe (although I would doubt that), but with webpack I cannot just disable the mangling for one library easily, and for our whole codebase the size definitely increases.

**Comment by RubenVerborgh** [comment]
Indeed, better to be consistent.
