### ISSUE TITLE
Support stream parsing in a browser context

### ISSUE THREAD

**Issue by acoburn** [rdfjs/N3.js#137]
I am trying to use a stream-based parser in a browser context (using browserify) along these lines:

```javascript
const parser = new N3.Parser();

fetch("http://localhost/rdf-resource")
    .then(res => parser.parse(res.body.getReader(), (err, quad) =>
        quad ? doSmthWithQuad(quad) : finish()))
```

The problem is that the N3Lexer expects that, for any non-string (in this case, it is a `ReadableStream`) , the tokenizer code assumes that the `input` object has an `.on` method. This works fine for Node.js Streams, but for a browser using the Fetch API, that assumption does not hold. One option is, of course, to read the response body into a string and pass that to the parser, but I'd like to avoid that, if possible.

I have found that by adding the following code to the `N3Lexer::tokenize` method, I am able to get this to work in a browser context.

```javascript
    if (typeof input === 'string') {
       ...
    }
    // If the input has a read method, it is a ReadableStream
    else if (typeof input.read === 'function') {
      this._input = '';
      input.read().then(function readStream({done, value}) {
        if (done) {
          if (self._input !== null)
            self._tokenizeToEnd(callback, true);
          return;
        } else if (self._input !== null) {
          self._input += new TextDecoder('utf-8').decode(value);
          self._tokenizeToEnd(callback, false);
        }    
        return input.read().then(readStream);
      });  
    }
    // Otherwise, the input must be a stream
    else {
        ...
    }
```

Or is there a better way to go about this?

**Comment by RubenVerborgh** [comment]
> One option is, of course, to read the response body into a string and pass that to the parser, but I'd like to avoid that, if possible.

But that's what your solution does? :wink:

> Or is there a better way to go about this?

Yeah, how do you feel about:

```JavaScript
const resource = await fetch("http://localhost/rdf-resource");
const parser = new N3.Parser();
parser.parse(await resource.text(), (err, quad) => quad ? doSmthWithQuad(quad) : finish(err));
```

**Comment by acoburn** [comment]
Ah yes, using `response.body.text()` is functionally equivalent (unless there is a _really_ large RDF document). Your suggestion works for me. Thanks!

**Comment by bergos** [comment]
I had the same problem, but to keep the streaming behavior and only change the API, I built a [wrapped version of fetch](https://github.com/bergos/nodeify-fetch) which returns Node streams. Works also in Node with no overhead.
