### ISSUE TITLE
Invalid term incorrectly parsed as a relative IRI

### ISSUE THREAD

**Issue by wouterbeek** [rdfjs/N3.js#138]
The following Turtle snippet:

```ttl
<entity.beeldbank_leiden_person:A.E._Stuur.> <x:x> <x:x> .
```

is currently parsed by N3 (assuming `{baseIRI:
'https://example.com/'}`):

```
subject: 
 NamedNode {
   id: 'https://example.com/entity.beeldbank_leiden_person:A.E._Stuur.' },
predicate: NamedNode { id: 'x:x' },
object: NamedNode { id: 'x:x' },
graph: DefaultGraph { id: '' } }
```

The subject term is treated as a relative IRI, but relative IRIs are
not allowed to contain a colon in their first path segment.  The
subject term is not an absolute IRI either, since the part before the
colon contains underscores (and this is not allowed).

Expected: The above Turtle snippet to result in an error.  For reference,
this is the behavior of the latest Serd parser:

```
$ serdi example.ttl 
error: example.ttl:1:5: bad subject
```

**Comment by RubenVerborgh** [comment]
Thanks, good find! With unfortunate consequences though: IRIs used to be relative when they were not absolute, now they can be invalid too. Hope a fix won't affect performance.

**Comment by RubenVerborgh** [comment]
Relevant part of RFC 3986:

>  a URI reference
   (Section 4.1) may be a relative-path reference, in which case the
   first path segment cannot contain a colon (":") character.
—https://tools.ietf.org/html/rfc3986#section-3.3

**Comment by RubenVerborgh** [comment]
Also, ❤️ Addo Stuur, without whom I'd never have gotten into Computer Science.

![winkind](https://user-images.githubusercontent.com/675313/41101083-6f3dc9b8-6a63-11e8-886a-cc762c134e82.jpg)
![thumbnail](https://user-images.githubusercontent.com/675313/41101088-71dda738-6a63-11e8-9d7c-958f40b739a0.jpg)

**Comment by wouterbeek** [comment]
@RubenVerborgh Yes, the passage from RFC 3986 is not in the grammar, but is required in order to make the standard non-ambiguous (otherwise some relative IRIs with a colon in their first path might as well be absolute IRIs, although oftentimes in a non-standardized scheme).

I'm not sure how to respond to the Addo Stuur post though...  I think I have colored the elephant BMP in ground school BTW.

**Comment by RubenVerborgh** [comment]
> I'm not sure how to respond to the Addo Stuur post though...

Well, you brought it up with `<entity.beeldbank_leiden_person:A.E._Stuur.>` :-)
I assumed he was kind of a hero among Dutch computer scientists.

**Comment by wouterbeek** [comment]
Haha, I hadn't noticed that.  The data came from Somewhere on the internet.
