### ISSUE TITLE
Add typescript defs

### ISSUE THREAD

**Issue by LaurensRietveld** [rdfjs/N3.js#139]
Shall we add a typescript definition file when the interface of version 1.x.x has settled? (in a similar fashion as how we added the ts definition to hdt-node)
Doing this should also involve deprecating the N3 definitions on definitely-typed, and replacing it with a stub

**Comment by RubenVerborgh** [comment]
> Shall we add a typescript definition file when the interface of version 1.x.x has settled?

Good idea. I would expect the majority of the definitions to be shared across RDF/js libraries, since we share a notion of Quad, Term, etc.

My only condition would be to have some kind of testing for the typings, so that we know when something breaks.

**Comment by rubensworks** [comment]
I'm working on updating the DefinitelyTyped typings here: https://github.com/rubensworks/DefinitelyTyped/tree/update/n3-rdfjs

This is however a blocker for this: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/26373

**Comment by rubensworks** [comment]
A PR has been opened to DefinitelyTyped with the new typings version: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/27982

Feel free to add your own review there if needed @RubenVerborgh.

**Comment by RubenVerborgh** [comment]
Thx! Let's follow up there.

**Comment by rubensworks** [comment]
New typings are now available at `@types/n3`.
