### ISSUE TITLE
Asynchronous

### ISSUE THREAD

**Issue by NicoLaval** [rdfjs/N3.js#140]
Parsers and Writers have callback which ensure that transactions are ended.
I don't find same mechanism on the store object.

So when we add quads to a store, how can we be sure that previous data is already persisted before launching a new action / query ?

**Comment by NicoLaval** [comment]
Gloups, sorry for my previous useless actions (suppress if you can).
Thxs for the response.
Have you an open source web app using N3 ? (I have other interrogations on store usage, I will open an other issue)

**Comment by NicoLaval** [comment]
> The N3.Store interface is synchronous, so data is stored as soon as the call ends.

It's curious.
I'm working on a React app, with an `Import` component which handle: 
`export const importIntoStore = (ttlString, graph) => {`
`       const parser = new N3.Parser();`
`       parser.parse(ttlString, (e, quad) => {`
`             if (quad) store.addQuad({ ...quad, graph: 'myGraph' });`
`       });`
`};`
Then I pushed (`react-router-dom`) to the `App` component and I just try to render a list of quads with:
`store.getQuads()`
Array is empty, and when I navigate to an other page and I come back, array is actually populated by quads.

**Comment by NicoLaval** [comment]
Insert a 1 millisecond timeout before pushing seems to fix the issue:
`setTimeout(() => this.props.history.push('/'), 1);`
But it seems to be a ugly hack.

**Comment by RubenVerborgh** [comment]
As I wrote above, the store is synchronous.

However, as you remarked, the parser is asynchronous. So what you need is:

```
parser.parse(ttlString, (e, quad) => {
  if (quad)
    store.addQuad({ ...quad, graph: 'myGraph' });
  else
    tellReactYoureDone();
});
};
```
