### ISSUE TITLE
Store reading

### ISSUE THREAD

**Issue by NicoLaval** [rdfjs/N3.js#141]
Writing into the store is quite easy but reading data seems to be more complicated.

**N3 doesn't support SPARQL, is it an upcoming feature ?**

I tried:

* rdfstore-js which is building on N3 but there are bugs and issues and it doesn't seems to be maintained.
* N3 store methods:
    * I would list DataStructureDefinition (id & label)
    * Triples:
`<myResource>   a   qb:DataStructureDefinition ;`
`                           dcterms:identifier       "id";`
`                           skos:prefLabel      "label";`
    * JS getter
`const getLiteral = (URI, predicat, graph) =>`
    `store.getQuads(`
		`namedNode(URI),`
		`namedNode(predicat),`
		`null,`
		`graph ? namedNode(graph) : null`
	`)[0].object.value;`
` `
`export const getDSDs = () => {`
`let DSDs = [];`
`	store.forSubjects(`
`		s =>`
`			DSDs.push({`
`				id: getLiteral(s.id, getURI('dcterms', 'identifier')),`
`				label: getLiteral(s.id, getURI('skos', 'prefLabel')),`
`			}),`
`		null,`
`		namedNode(getURI('qb', 'DataStructureDefinition'))`
`	);`
`	return DSDs;`
`};`

Can I doing better / shorter ?

Thxs

**Comment by RubenVerborgh** [comment]
> Writing into the store is quite easy but reading data seems to be more complicated.

Reading data is as easy as writing it.

> N3 doesn't support SPARQL

Ah, you want to query :-)

< is it an upcoming feature ?

No, it is out of scope for N3.js, but check out the [Comunica](https://github.com/comunica/comunica/) project.
