### ISSUE TITLE
Make addPrefix accept URLs that do not end in # or /

### ISSUE THREAD

**Issue by artonio** [rdfjs/N3.js#143]
in N3Writer.js in addPrefixes function, there is a check for the validity of the URI which should end with '#' or '/'. So if the URI of the prefix is malformed it will fail silently. Have you considered throwing an Error() if the passed URI is malformed?

DefinitelyTyped tests contain some malformed URI in prefixes in _function test_serialize()_.

**Comment by RubenVerborgh** [comment]
> in N3Writer.js in addPrefixes function, there is a check for the validity of the URI which should end with '#' or '/'.

Why should the prefix URL end in '#' or '/'? The following is perfectly valid Turtle:

```turtle
PREFIX ex: <http://ex>
ex:ample ex:ample ex:ample.
```

**Comment by RubenVerborgh** [comment]
Right, I wonder whether I can relax this constraint (and don't remember why I introduced it in the first place). Writer is purposely not abbreviating on every possible occasion (would be too expensive), but it seems that abbreviations in such cases would be okay.

**Comment by artonio** [comment]
While there are no strict rules in RDF world, it is believed to be a good practice to end the URI's with '#' or '/' as outlined in:
https://www.w3.org/TR/ldp-bp/#predicate-uris-should-be-http-urls - Section 2.6

**Comment by RubenVerborgh** [comment]
Yeah, I'd just prefer not to throw an exception if the user chooses to do so anyway, and you are right that the current “ignore” behavior is weird too.
