### ISSUE TITLE
RDFJS Source interface on N3Store

### ISSUE THREAD

**Issue by rubensworks** [rdfjs/N3.js#145]
It would be nice if N3Store would implement the [Source](http://rdf.js.org/#source-interface) interface.
This would make it possible to for example use N3Store as a direct back-end in comunica, instead of [having to wrap it](https://github.com/comunica/comunica/tree/master/packages/actor-init-sparql-rdfjs#usage).

This interface defines the match method as follows:
```
Stream match(optional (Term or RegExp) subject, optional (Term or RegExp) predicate, optional (Term or RegExp) object, optional (Term or RegExp) graph);
```
Unfortunately, this includes regexes, so this can't be implemented efficiently in N3Store (unless for terms that are _not_ a regex)

**Comment by rubensworks** [comment]
Yep, that should be an easy an clean way to do it!

It might be possible to optimize a bit and apply the regexes directly on each index level, to avoid iterating over (potentially large) index values for terms that don't match anyways. But that won't be as straightforward to implement, so this could be future work™.

**Comment by iddan** [comment]
Started working on it at https://github.com/rdfjs/N3.js/pull/160

**Comment by RubenVerborgh** [comment]
Implemented in https://github.com/rdfjs/N3.js/pull/174.
