### ISSUE TITLE
Base IRI support in N3Writer

### ISSUE THREAD

**Issue by rkaw92** [rdfjs/N3.js#157]
Say we're parsing the below document, for which the base IRI is `http://example.org/persons`:
```
@prefix foaf: <http://xmlns.com/foaf/0.1/> .

<#green-goblin> foaf:name "Green Goblin" .

<#spiderman> foaf:name "Spiderman" .
```

Then the parser shall emit quads where the subject is a fully-resolved URI such as `http://example.org/persons#spiderman`. This is fine and correct.

However, the user is then quite incapable of re-constructing this convenient notation (using relative "fragments") with the N3Writer, because it has no concept of base IRI.

Granted, a similar output could be achieved by defining a prefix. However, then we get `prefix:#spiderman` or `prefix:spiderman` (depending on how we've set up the prefix). This is not the same as we got on input.

I think it would be great if the writer could "compact" full resource URIs for the subjects using the base IRI of the written document. For this, the feature outlined in #81 may be useful - however, it is not required, as it would be perfectly fine to specify `baseIRI` in the Writer constructor, same way we do in the Reader's.

**Comment by tgoprince** [comment]
Is there a plan to implement this feature? I would also like to have it.

**Comment by RubenVerborgh** [comment]
@tgoprince Has been implemented in https://github.com/rdfjs/N3.js/commit/07b0f35993893e50558570bfbfb7f1b555a954be, starting [v1.8.0](https://github.com/rdfjs/N3.js/releases/tag/v1.8.0).
