### ISSUE TITLE
replace stream with readable-stream

### ISSUE THREAD

**Issue by bergos** [rdfjs/N3.js#159]
The readme of [readable-stream](https://www.npmjs.com/package/readable-stream) says already why it should be used:

> If you want to guarantee a stable streams base, regardless of what version of Node you, or the users of your libraries are using, use readable-stream only and avoid the "stream" module in Node-core

Also I have a better experience using `readable-stream` browser environments. If `stream` is used, you don't know which fallback implementation will be used.

**Comment by RubenVerborgh** [comment]
Hmm, but we're also using `Writable`, so would that still hold?

I have the feeling that, when using webpack, people can select the implementation they want/need.

**Comment by bergos** [comment]
`readable-stream` provides all kinds of streams defined in the Node.js `stream` module. Also [Writable](https://www.npmjs.com/package/readable-stream#usage).

I'm sure it's somehow possible to select the stream implementation used by webpack, but the package creating the streams knows best which version to use. The [blog post](https://r.va.gg/2014/06/why-i-dont-use-nodes-core-stream-module.html) linked in the readme of the package describes it very well. Also why it's relevant for Node.js (at least it was once, not sure about the future).

**Comment by RubenVerborgh** [comment]
Thanks, that's a confusing name then 🙂

I find the necessity of this very hard to assess; the blog post is from 2014 so predates a lot of webpack functionality. Is this still a problem in the browser? I do see 15M weekly downloads though…

Also given that N3.js only uses a very limited subset…

Summarizing, I don't have sufficient background and arguments to decide on whether this is a good or necessary idea. @bergos Are you guys using it, and out of a specific necessity or problem, or just as a precaution?

Perhaps @rubensworks knows more?

**Comment by bergos** [comment]
I think at the time the blog post was written, the focus was more Node.js and breaking changes between some 0.x versions. I'm not sure if that could happen again in the future.

For webpack users with not so much Node.js experience it's more relevant that there is also a [stream](https://www.npmjs.com/package/stream) package on npm, which can be confusing (I was ask not only once why I'm using such an old library). Also version tracking is not directly possible via package.json or package-lock.json.

Just my personal thoughts and experience. Besides [this blog post ](https://www.nearform.com/blog/welcome-readable-stream-3/) from August, I could not find any recent information. Would be happy about any links for more up to date information.

I created this issue cause @semanticfire had a [problem](https://gitter.im/rdf-ext/discussions?at=5c2f77658dafa715c73f89f9), but could be also a problem of the [webpack-library-starter](https://github.com/krasimir/webpack-library-starter) package he was using.

**Comment by RubenVerborgh** [comment]
From what I'm reading there, @semanticfire might want to configure webpack to use `readable-stream` (or anything but browserify really).

**Comment by RubenVerborgh** [comment]
I think I will close this for now, unless there are concrete bugs that require this as a solution. Given that there are no concrete issues now, depending on this package might make things bad or worse, and we wouldn't know.

But thanks for filing @bergos, and happy to reconsider at any point in the future.

**Comment by RubenVerborgh** [comment]
Continued in #216.
