### ISSUE TITLE
N3 doesn't sanitize URLs on write

### ISSUE THREAD

**Issue by yamalight** [rdfjs/N3.js#166]
N3 doesn't seem to sanitize URLs before writing them. Is that intended?
E.g. the following code:
```js
const writer = N3.Writer();
writer.addQuad(
  namedNode('http://example.org/publication/123'),
  namedNode('http://example.org/doi'),
  namedNode('http://onlinelibrary.wiley.com/doi/10.1002/(SICI)1097-0231(19970830)11:13<1435::AID-RCM24>3.0.CO;2-A/pdf')
);
writer.end((error, result) => console.log(result));
```

Will produce the following malformed triple:
```
<http://example.org/publication/123> <http://example.org/doi> <http://onlinelibrary.wiley.com/doi/10.1002/(SICI)1097-0231(19970830)11:13<1435::AID-RCM24>3.0.CO;2-A/pdf>.
```

Adding `encodeURI` wrap over that last URI fixes it. But I expected that to be in the lib itself 🤔 
What's the reasoning here? Would you be open to PR that adds encodeURI before writes?

**Comment by RubenVerborgh** [comment]
> N3 doesn't seem to sanitize URLs before writing them. Is that intended?

Yes. Garbage in, garbage out 🙂
N3.js itself never generates invalid URLs (the parser will reject them), so you're responsible for whatever you put into it 🙂

> Adding `encodeURI` wrap over that last URI fixes it. But I expected that to be in the lib itself 🤔

Ooh, but you should never use `encodeURI`. It's a stopgap method that selectively sanitizes URLs, but not quite, as no method cannot distinguish between already escaped URLs or not. Like: should those `%`s be escaped (again) or not? Use encodeURIComponent to sanitize parts of a URL before you construct it.

Also note that differently escaped URLs, while identical for protocols like HTTP, are different URIs for RDF.

> Would you be open to PR that adds encodeURI before writes?

That would butcher `<http://example.com/hello%20world>` into `<http://example.com/hello%2520world>`, so I wouldn't be able to accept it.

**Comment by yamalight** [comment]
@RubenVerborgh that makes perfect sense now that you'd explained it 😅 
Cannot think of a way to handle all cases you've described. Will come back if I got any good ideas 😂
