### ISSUE TITLE
Lists re-encoded if stored then written

### ISSUE THREAD

**Issue by radicand** [rdfjs/N3.js#167]
Pardon if I have the wrong terminology here, new to the space.

I came across an issue creating a large list - N3.Writer correctly encodes the list under the below circumstances:

```js
let N3 = require('n3');
let { DataFactory } = N3;
let { namedNode, literal, defaultGraph, quad } = DataFactory;
writer = N3.Writer();

writer.addQuad(
  namedNode('http://example.org/cartoons#Mammy'),
  namedNode('http://example.org/cartoons#hasPets'),
  writer.list([
    namedNode('http://example.org/cartoons#Tom'),
    namedNode('http://example.org/cartoons#Jerry'),
  ])
);
writer.end((error, result) => console.log(result));
```
The result is then (as expected):
```
<http://example.org/cartoons#Mammy> <http://example.org/cartoons#hasPets> (<http://example.org/cartoons#Tom> <http://example.org/cartoons#Jerry>).
```

But if you store all quads first before writing as in:

```js
let N3 = require('n3');
let { DataFactory } = N3;
let { namedNode, literal, defaultGraph, quad } = DataFactory;
writer = N3.Writer();
store = N3.Store();

store.addQuad(
  namedNode('http://example.org/cartoons#Mammy'),
  namedNode('http://example.org/cartoons#hasPets'),
  writer.list([
    namedNode('http://example.org/cartoons#Tom'),
    namedNode('http://example.org/cartoons#Jerry'),
  ])
);
writer.addQuads(store.getQuads())
writer.end((error, result) => console.log(result));
```
The result is then (note the extra <>):
```
<http://example.org/cartoons#Mammy> <http://example.org/cartoons#hasPets> <(<http://example.org/cartoons#Tom> <http://example.org/cartoons#Jerry>)>.
```

It seems like this can be solved by adding a new "ListNode" function and class to DataFactory, similar to NamedNode (to bypass the re-encoding that happens in _encodeIriOrBlank), detected by fromId if id[0] === `(`. I've done something similar in my local codebase and it's working as expected; let me know if a PR is worthwhile or if you'd prefer to handle it differently.

**Comment by RubenVerborgh** [comment]
Hi @radicand,

The `Writer#list` method is for exclusive use with the `Writer` instance to which it belongs. It is a pretty-printing method, which should not be combined with the `Store` at all.

In the store, you should place regular `rdf:first` and `rdf:rest` triples.

**Comment by radicand** [comment]
Noted, thanks for clarification.

**Comment by renyuneyun** [comment]
I'm encountering this today, and found this old issue.

From an ergonomics point of view, why would `Store.addQuad()` accept the output of `Writer.list()` in the first place? 
I mean, why does `Quad_Object[]` both represent *a JS list containing several things (that can be objects)* and *an RDF list containing several things*? Shouldn't they be two distinct types?

**Comment by RubenVerborgh** [comment]
> Thus, shouldn't they be two distinct types?

They are. The list node is `SerializedTerm extends Term`, which just so happens to match the input type of `Store.addQuad()`.
