### ISSUE TITLE
Error parsing 'a' without whitespace

### ISSUE THREAD

**Issue by wouterbeek** [rdfjs/N3.js#169]
The following Turtle file is not parsed, possibly because the `a` appears with no whitespace surrounding it:

```ttl
[a<>].
[a[]].
[a()].
<>a<>.
<>a[].
<>a().
```

If I read the standard correctly, whitespace is not required around the `a`.

**Comment by RubenVerborgh** [comment]
But this is not serd? 🙂

**Comment by wouterbeek** [comment]
Sorry for that, I've changed the ticket accordingly.  (Serd also has issues with the above Turtle file.)

**Comment by RubenVerborgh** [comment]
Thanks, fixed!
