### ISSUE TITLE
Problem with node types in built react app 

### ISSUE THREAD

**Issue by mikael1234** [rdfjs/N3.js#176]
Everything works fine with local react test server (npm start): N3.Util.isNamedNode(object) returns true for named nodes, and object.termType returns "NamedNode" for named nodes.

But when app is built (npm run build) and copied to another server, N3.Util.isNamedNode(object) returns false for everything and object.termType returns "t" for everything.

Maybe I have done something wrong? Any ideas?

**Comment by RubenVerborgh** [comment]
Minification: https://github.com/rdfjs/N3.js/issues/172

Fixed in v1.1.1.
