### ISSUE TITLE
baseIRI is ignored when certain formats are specified

### ISSUE THREAD

**Issue by Ysgorg** [rdfjs/N3.js#177]
When the baseIRI is given, n3 seems to apply this correctly except if certain formats are also specified. When running the code below, there are errors when baseIRI is specified and the format is either "application/n-quads" or "application/n-triples". The error message reads "Invalid IRI on line 1". This is with n3 version 1.1.1. The mime-types are taken from the w3c specification for each format. 

```
const N3 = require('n3')
async function testWithFormat(data, format){
  const parser = new N3.Parser({baseIRI:'http://example.org/', format:format});
  try {
    await parser.parse(data);
    console.info(`Successfully parsed ${data} for format ${format}.`)
  } catch(e){
    console.error(`Failed to parse ${data} for format ${format}. Error:`,e)
  }
}

async function run(){
  await testWithFormat('<a> <b> <c> <d>.','application/n-quads');
  await testWithFormat('<a> <b> <c> <d>.');
  await testWithFormat('<a> <b> <c>.','text/turtle');
  await testWithFormat('<a> <b> <c>.');
  await testWithFormat('<a> <b> <c>.','application/n-triples');
  await testWithFormat('<a> <b> <c>.');
  await testWithFormat('<g>{<a> <b> <c>}','application/trig');
  await testWithFormat('<g>{<a> <b> <c>}');
}

run().catch(console.error)
```

**Comment by rubensworks** [comment]
AFAIK, N-Quads and N-Triples don't allow baseIRIs to be set, which is probably why N3.js doesn't apply them, and simply errors. So I think this is intentional behaviour.

**Comment by Ysgorg** [comment]
I think `'<a> <b> <c> <d>.'` can only be interpreted as n-quads. If that's the case I would expect N3 to also throw an error for the second test, where the format is undefined. Instead it produces the following quad: 

```
[ Quad {
    subject: NamedNode { id: 'http://example.org/a' },
    predicate: NamedNode { id: 'http://example.org/b' },
    object: NamedNode { id: 'http://example.org/c' },
    graph: NamedNode { id: 'http://example.org/d' } } ]
```

**Comment by RubenVerborgh** [comment]
> I think `'<a> <b> <c> <d>.'` can only be interpreted as n-quads. If that's the case I would expect N3 to also throw an error for the second test, where the format is undefined.

[By default, N3.Parser parses a permissive superset of Turtle, TriG, N-Triples, and N-Quads.](https://github.com/rdfjs/N3.js/tree/adeef0a13478e4cd74a2a792d411f9a23b31c3b4#from-an-rdf-document-to-quads)

**Comment by Ysgorg** [comment]
I understand this as being by design then. I'll close this issue, thank you.
