### ISSUE TITLE
N3Parser reports syntax error for escaped quotes at the end of an object string

### ISSUE THREAD

**Issue by CadanoX** [rdfjs/N3.js#178]
When parsing data in the Turtle format with escaped quotes inside the object string, the parsing fails if the quote is at the end of the string.

Example:

```
const data = `
    @prefix owl:  <http://www.w3.org/2002/07/owl#> .
    <http://purl.bioontology.org/ontology/ICD9CM/488.89> a owl:Class ;
    <http://purl.bioontology.org/ontology/ICD9CM/SOS> """Excludes: \"intestinal flu\" [viral gastroenteritis] (008.8)"""^^xsd:string ; .
    <http://purl.bioontology.org/ontology/ICD9CM/785.6> a owl:Class ;
    <http://purl.bioontology.org/ontology/ICD9CM/ICE> """Lymphadenopathy; \"Swollen glands\""""^^xsd:string ; .`

const parser = new N3.Parser({ baseIRI: 'http://purl.bioontology.org/ontology/ICD9CM/' });
let quads = parser.parse(data);
```

Uncaught Error: Unexpected ""^^xsd:string on line 6.

The async version stops on such an encounter without throwing an error.

**Comment by RubenVerborgh** [comment]
There is an error in your snippet above; you should write the backslash as `\\` to escape for JavaScript. The correct code is:

```JavaScript
const data = `
    @prefix owl:  <http://www.w3.org/2002/07/owl#> .
    <http://purl.bioontology.org/ontology/ICD9CM/488.89> a owl:Class ;
    <http://purl.bioontology.org/ontology/ICD9CM/SOS> """Excludes: \\"intestinal flu\\" [viral gastroenteritis] (008.8)"""^^xsd:string ; .
    <http://purl.bioontology.org/ontology/ICD9CM/785.6> a owl:Class ;
    <http://purl.bioontology.org/ontology/ICD9CM/ICE> """Lymphadenopathy; \\"Swollen glands\\""""^^xsd:string ; .`
```

**Comment by jimsmart** [comment]
I'm a little curious about this part:

> The async version stops on such an encounter without throwing an error.

...should this in fact throw an error? What is the expected behaviour here?

**Comment by RubenVerborgh** [comment]
> ...should this in fact throw an error? What is the expected behaviour here?

It doesn't throw, but passes the error through the callback.
