### ISSUE TITLE
Class extends value undefined is not a constructor or null

### ISSUE THREAD

**Issue by mahmuthanb** [rdfjs/N3.js#181]
Hi guys, i'm getting this error when the parser code is triggered. I didn't find any problem. Can anyone help me ? You can see the screenshots of error and codes at the bottom. Thanks in advance.

**ERROR TypeError: Class extends value undefined is not a constructor or null**
    at Object../node_modules/n3/lib/N3StreamParser.js (N3StreamParser.js:6)
    at __webpack_require__ (bootstrap:78)
    at Object../node_modules/n3/N3.js (N3.js:7)
    at __webpack_require__ (bootstrap:78)
    at UploaderComponent.push../src/app/modules/upload/uploader/uploader.component.ts.UploaderComponent.n3parser (uploader.component.ts:25)
    at Object.eval [as handleEvent] (UploaderComponent.html:54)
    at handleEvent (core.js:10251)
    at callWithDebugContext (core.js:11344)
    at Object.debugHandleEvent [as handleEvent] (core.js:11047)
    at dispatchEvent (core.js:7710)

![error-code](https://user-images.githubusercontent.com/10919260/61779574-976db980-ae09-11e9-9e04-8e9340f7b1ae.jpg)
![error-output](https://user-images.githubusercontent.com/10919260/61779575-976db980-ae09-11e9-8303-af17cc6780cd.jpg)

**Comment by RubenVerborgh** [comment]
Likely a packaging problem; would need minimal example to reproduce.

**Comment by mahmuthanb** [comment]
This zip contains uploader.component.ts and my packages.json file. Any other required file ?
[error.zip](https://github.com/rdfjs/N3.js/files/3425965/error.zip)

**Comment by RubenVerborgh** [comment]
Exact steps to reproduce, please.

**Comment by mahmuthanb** [comment]
You can get the project here: 
https://github.com/mahmuthanb/N3ParserApp

**Installed Packages:**

Angular CLI: 8.1.2
Node: 10.16.0
OS: linux x64
Angular: 8.1.2
Package                                       Version
-----------------------------------------------------------
@angular-devkit/architect             0.801.2
@angular-devkit/build-angular      0.801.2
@angular-devkit/build-optimizer    0.801.2
@angular-devkit/build-webpack     0.801.2
@angular-devkit/core                   8.1.2
@angular-devkit/schematics        8.1.2
@ngtools/webpack                       8.1.2
@schematics/angular                   8.1.2
@schematics/update                0.801.2
rxjs                                  6.4.0
typescript                        3.4.5
webpack                         4.35.2

----------------------------------------------------------------------

**Comment by RubenVerborgh** [comment]
Could you please tell me the steps, one by one, I need to take to reproduce the error? You are pointing to code; that’s step 1. Now please the others 🙂

**Comment by mahmuthanb** [comment]
I've created a sample project then i've run the code
`npm i` 
then added the n3 package
`npm install n3`
then added sample parser codes into app.component's constructor.
`const = require('n3');`
`const { DataFactory } = N3;`
`const { namedNode, literal, defaultGraph, quad } = DataFactory;`
`const myQuad = quad(
`namedNode('https://ruben.verborgh.org/profile/#me'),`
 `namedNode('http://xmlns.com/foaf/0.1/givenName'),`
  `literal('Ruben', 'en'),`
 ` defaultGraph(),`
`);`
`console.log(myQuad.subject.value);         // https://ruben.verborgh.org/profile/#me`
`console.log(myQuad.object.value);          // Ruben`
`console.log(myQuad.object.datatype.value); // http://www.w3.org/1999/02/22-rdf-syntax-ns#langString`
`console.log(myQuad.object.language);       // en`

then i tried to start app but got an error like

> ERROR in src/app/app.component.ts:12:16 - error TS2591: Cannot find name 'require'. Do you need to install type definitions for node? Try `npm i @types/node` and then add `node` to the types field in your tsconfig. 

then tried to install via  `npm i @types/node`  and added "node" in compilerOptions's types node in tsconfig.app.json.
After that tried to `npm start` again and got error like ;

> ERROR in ./node_modules/n3/lib/N3Store.js
Module not found: Error: Can't resolve 'stream' in '/home/mahmuthanb/Desktop/projects/n3parserapp/node_modules/n3/lib'
ERROR in ./node_modules/n3/lib/N3StreamParser.js
Module not found: Error: Can't resolve 'stream' in '/home/mahmuthanb/Desktop/projects/n3parserapp/node_modules/n3/lib'
ERROR in ./node_modules/n3/lib/N3StreamWriter.js
Module not found: Error: Can't resolve 'stream' in '/home/mahmuthanb/Desktop/projects/n3parserapp/node_modules/n3/lib'

then fixed it with `npm i stream` 
after that tried to start project via `npm i start`
now i got that same error screen that i've added screenshots above in first comment.
I'd tried to run this project on Ubuntu 18.04.2 (now working on it), Windows 10 x64 and Ubuntu 18.04

**Comment by RubenVerborgh** [comment]
This is definitely a packaging problem; stream is a built-in Node module.

**Comment by mahmuthanb** [comment]
So, whats your stream package version or what should i install for stream package ?

**Comment by RubenVerborgh** [comment]
stream is built into Node. It is not an npm module. You need to configure your package manager to include it.
