### ISSUE TITLE
Blank nodes naming

### ISSUE THREAD

**Issue by jacoscaz** [rdfjs/N3.js#183]
Hello!

As of version `1.2.0`, the following code

```
const trig = `
  <did:gsync:Jc8eE87deLySptJeJ9L4mD#lei/03a15c2c20c70b75aba22f792b3b5da82442f37cd740b839a0ab6c74ebd611ed> {
    _:ub26bL17C87 <http://lei.info/voc/l1/registrationAuthorityEntityID> "574206" .
    _:ub26bL17C87 a <http://lei.info/voc/l1/RegistrationAuthority> ;
  }
`;

const parser = new n3.Parser({ format: 'application/trig' });

parser.parse(trig, (err, quad, prefixes) => {
  if (err) throw err;
  if (!quad) return;
  console.log(quad);
});
```

results in quads whose blank nodes have slightly different labels than I had expected:

```
Quad {
  subject: BlankNode { id: '_:b0_ub26bL17C87' },
  predicate:
   NamedNode { id: 'http://lei.info/voc/l1/registrationAuthorityEntityID' },
  object: Literal { id: '"574206"' },
  graph:
   NamedNode {
     id:
      'did:gsync:Jc8eE87deLySptJeJ9L4mD#lei/03a15c2c20c70b75aba22f792b3b5da82442f37cd740b839a0ab6c74ebd611ed' } }
Quad {
  subject: BlankNode { id: '_:b0_ub26bL17C87' },
  predicate:
   NamedNode { id: 'http://www.w3.org/1999/02/22-rdf-syntax-ns#type' },
  object:
   NamedNode { id: 'http://lei.info/voc/l1/RegistrationAuthority' },
  graph:
   NamedNode {
     id:
      'did:gsync:Jc8eE87deLySptJeJ9L4mD#lei/03a15c2c20c70b75aba22f792b3b5da82442f37cd740b839a0ab6c74ebd611ed' } }
```

It seems like blank nodes labels are getting prefixed with `b0_`. As this happens consistently, the parser still ends up producing quads that are equivalent to the original `TriG` source. It's just the blank nodes that are named differently. Is this behavior expected?

**Comment by RubenVerborgh** [comment]
> Is this behavior expected?

Yes; and it far outdates v1.2.0.

The idea is that, if you parse two different documents that happen to use the same local blank node identifier, those should map to different blank nodes. Prefixing is an easy way to guarantee this.

You can change this with the `blankNodePrefix` option to the `Parser` constructor.

**Comment by jacoscaz** [comment]
Hello @RubenVerborgh . Would you accept a PR mentioning this parameter in `README.md`? I'd be happy to contribute.

**Comment by RubenVerborgh** [comment]
For sure, thanks! Extra docs are always welcome.

**Comment by jacoscaz** [comment]
Made a PR  - #184 . No objections to closing this one.
