### ISSUE TITLE
Unhandled error when passing long literals

### ISSUE THREAD

**Issue by LaurensRietveld** [rdfjs/N3.js#185]
When passing long literals, we might be running into RangeErrors (see #128). 
Such errors are not handled properly by N3, resulting in an unhandled exception. To avoid such fatal exceptions, it would be nice if there is some better error handling

To reproduce, run `./perf/N3Parser-perf.js` with the file uploaded here https://github.com/rdfjs/N3.js/issues/128#issuecomment-555487408

ps. To clarify: this is not about fixing/avoiding RangeErrors, but merely about properly emitting errors from N3

**Comment by RubenVerborgh** [comment]
I think in this particular case, we should actually avoid the error being thrown in the first place, by fixing #128. I will leave this one open too though.
