### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by blake-regalia** [rdfjs/N3.js#186]
Can we update this line? It's not true anymore:

> - **fast** – by far the [fastest spec-compatible parser in JavaScript](https://github.com/rdfjs/N3.js/tree/master/perf)

graphy has been spec-compatible for quite some time now.

**Comment by RubenVerborgh** [comment]
> graphy has been spec-compatible

Happy to change, but I see 279 / 298 Turtle spec tests, 57 / 68 N-Triples, 320 / 339 TriG, 73 / 85 N-Quads. It's in particular all the `-bad-` tests that are failing on me. Is that correct, or do I need to do something special for error handling?

**Comment by blake-regalia** [comment]
It may depend on how you are running the tests and which branch/version you are using. I will double check all the test cases right now and post back soon.

**Comment by RubenVerborgh** [comment]
Thanks. FYI was a fresh npm install.

**Comment by blake-regalia** [comment]
The 3.2.2 library passes all tests. If you are using a third party test kit you'll need to pass the appropriate flags to the reader such as `validate: true` and `maxStringLength`. Otherwise, the repo's test kit handles all setup for specs. https://travis-ci.org/blake-regalia/graphy.js/builds/491138776

**Comment by RubenVerborgh** [comment]
Thanks for testing. Looks good with `rdf-test-suite`; I have 4 test failures left, but they all are related to `baseIRI`. How am I supposed to pass it?

Reference code:

```JavaScript
// parser.js
const read = require('graphy').content.ttl.read;
const arrayify = require('arrayify-stream');
const streamify = require('streamify-string');

module.exports = {
  parse: function (data, baseIRI, options) {
    return arrayify(streamify(data).pipe(
      read({ baseIRI, validate: true })
    ));
  },
};
```

```bash
npx rdf-test-suite parser.js http://w3c.github.io/rdf-tests/turtle/manifest.ttl -c .rdf-test-suite-cache/
```

**Comment by blake-regalia** [comment]
Thanks! It seems the documentation is wrong. The key should actually be `baseURI`... I will update the docs now. I recall this was changed before release to reflect https://www.w3.org/TR/turtle/ and the fact that it is actually a URI and not an IRI.

**Comment by RubenVerborgh** [comment]
Confirmed to fully work now.

**Comment by RubenVerborgh** [comment]
Amazing work, @blake-regalia. Celebrated with b2ff96d35ed586fce1a02c567fb3ba9c10272598!
