### ISSUE TITLE
How to store quads during parsing from stream?

### ISSUE THREAD

**Issue by MrLugh** [rdfjs/N3.js#187]
Hi guys! hope you are well

some questions about reading triples from streams:

1: how can i store from streams?
`
const st = new N3.Store();
response.body
    .pipe(zlib.createGunzip())
    .pipe(new StreamParser())
    .pipe(processTripleFnAndStore ????)
`

2: i have a model {name: string, age: number}
it requires 2 rows in a triples file, suppose file is ordered by subject:
how can i read from stream, create instances of myModel and store those in an array to be printable on the finish event? (without using "global scope/context'

3: how much triples can be saved on the store? what about max size for it?

**Comment by RubenVerborgh** [comment]
@MrLugh Questions 1 and 2 seem to be more related to Node.js streams and JavaScript programming in general; I suggest https://gitter.im/rdfjs/

> 3: how much triples can be saved on the store? what about max size for it?

The limit is the RAM allocated to the Node.js process, and also depends on the size of your URIs and literals. So it's not a library limit, but a memory limit.
