### ISSUE TITLE
Method to distinguish whether datatype was specified or not

### ISSUE THREAD

**Issue by NeilGraham** [rdfjs/N3.js#195]
With N3 version 1.2.0, using the `N3.Parser` we are able to distinguish simple literals from `xsd:string` literals using the `id` property on the `Literal`
```javascript
const N3 = require("n3");
const nqParser = new N3.Parser({format:'N-Quads'});

// xsd:string Literal
const quadArr1 = nqParser.parse('<a:> <a:> "abc"^^<http://www.w3.org/2001/XMLSchema#string>.');
const literal1 = quadArr1[0].object;
console.log(literal1.id);
// Output: "abc"^^http://www.w3.org/2001/XMLSchema#string

// Simple Literal
const quadArr2 = nqParser.parse('<a:> <a:> "abc".');
const literal2 = quadArr2[0].object;
console.log(literal2.id);
// Output: "abc"
```
`N3.Writer` output does not include the datatype on all literals with the datatype `xsd:string`, including simple literals. If we specified the `xsd:string` datatype on a literal, we would append it back onto the literal after passing it through the `N3.Writer`; If we did not specify a datatype, we would leave it off.

With N3 version 1.3.5, there does not seem to be a distinction between simple literals and `xsd:string` literals. The output of `Literal.id` for both is now `"abc"`

The [RDF 1.1 Specification](https://www.w3.org/TR/rdf11-concepts/#section-Graph-Literal) does state that simple literals are syntactic sugar for `xsd:string` (or `rdf:langString` if a language tag is specified), which does prove the point of this change. However, we would like to have the distinction between whether the `xsd:string` datatype was specified or not.

**Comment by RubenVerborgh** [comment]
Hi @NeilGraham,

> With N3 version 1.2.0

That's not the latest one though; I strongly recommend 1.3.5.

> // Output: "abc"^^http://www.w3.org/2001/XMLSchema#string

That would be `"abc"^^http://www.w3.org/2001/XMLSchema` actually.

But

```
const quadArr1 = nqParser.parse('<a:> <a:> "abc"^^<http://www.w3.org/2001/XMLSchema#string>.');
console.log(quadArr1[0].object.datatype.value);
const quadArr2 = nqParser.parse('<a:> <a:> "abc".');
console.log(quadArr2[0].object.datatype.value);
```

will give

```
http://www.w3.org/2001/XMLSchema#string
http://www.w3.org/2001/XMLSchema#string
```

**Comment by NeilGraham** [comment]
@RubenVerborgh Sorry about that, I meant the following
``` javascript
const quadArr1 = nqParser.parse('<a:> <a:> "abc"^^<http://www.w3.org/2001/XMLSchema#string>.');
```
Not
``` javascript
const quadArr1 = nqParser.parse('<a:> <a:> "abc"^^<http://www.w3.org/2001/XMLSchema#>.');
```

**Comment by RubenVerborgh** [comment]
When running that on 1.3.5, you will get

```
"abc"
"abc"
```

**Comment by RubenVerborgh** [comment]
> With N3 version 1.3.5, there does not seem to be a distinction between simple literals and `xsd:string` literals. The output of `Literal.id` for both is now `"abc"`

Indeed; this is according to the specification:

> If there is no datatype IRI and no language tag, the datatype is xsd:string.
—https://www.w3.org/TR/turtle/#turtle-literals

They are just syntactical variants of the same thing; the difference in syntax has no meaning.

Please don't use the internal `.id` property; I recommend `.datatype.value` instead.

**Comment by NeilGraham** [comment]
I can understand how this would require unnecessary special casing. We'll begin conforming to this change.
