### ISSUE TITLE
Parsing of non-leading zero doubles/decimals

### ISSUE THREAD

**Issue by thomasdegroot18** [rdfjs/N3.js#203]
We wanted to parse the following file with the N3 library <http://qudt.org/2.1/vocab/unit>. But when parsing it we hit an Syntax error: `Unexpected ".171e-11" on line 13710.` 
When looking into the [RDF turtle spec](https://www.w3.org/TR/turtle/#grammar-production-DECIMAL), to check if the turtle was incorrectly formatted, we noticed that, this is indeed correctly formatted according to the turtle Spec. 

So we tried testing it with an minimal example:
```
const parser = new Parser({ format: "text/turtle" });
parser.parse("<><>.1e0.");
```

And we noticed that this example is also not parsed by the N3 library. Where as according to the [RDF turtle spec](https://www.w3.org/TR/turtle/#grammar-production-DECIMAL) it should be able to parse this line. 

Could this be a possible bug in the N3 library?

**Comment by RubenVerborgh** [comment]
This indeed seems to be a bug in the `DOUBLE` production rule, thanks!
