### ISSUE TITLE
Prefix application/trig named graph clause with `GRAPH `

### ISSUE THREAD

**Issue by NeilGraham** [rdfjs/N3.js#204]
It would be useful to have the option to prefix each named graph clause with `GRAPH ` when writing to `application/trig`. With this, RDF/JS quads that contain Named Graphs can be passed directly into a SPARQL query.

#### Graph clause prefix: `""`
```sparql
DELETE {
  # START: Write application/trig
  <g:0> {
    <s:0> <p:0> <o:0> .
  }
  # END: Write application/trig
} WHERE {}
```
- Current implementation
- Invalid SPARQL query

#### Graph clause prefix: `"GRAPH "`
```sparql
DELETE {
  # START: Write application/trig
  GRAPH <g:0> {
    <s:0> <p:0> <o:0> .
  }
  # END: Write application/trig
} WHERE {}
```
- Valid SPARQL query

**Comment by RubenVerborgh** [comment]
That seems out of N3.js scope though; rather in scope of [SPARQL.js](https://github.com/RubenVerborgh/SPARQL.js) (which already has this functionality).

**Comment by NeilGraham** [comment]
Apologies for keeping this ticket open for so long.
