### ISSUE TITLE
Destructuring assignment in the library make the library incompatible with IE11

### ISSUE THREAD

**Issue by Ladone3** [rdfjs/N3.js#206]

**Comment by Ladone3** [comment]
Hello. Working on my project I faced this issue. Once I include the latest version of the library in my project I can't work with IE11 anymore. Yes I can write some specific build-script and prebuilt the library, but for now it's easier to use the old version. If you solve this issue it can make things a lot it easier.

**Comment by RubenVerborgh** [comment]
Sorry, we're not testing on Internet Explorer anymore. I suggest using a packer indeed.
