### ISSUE TITLE
Issue with stream imports

### ISSUE THREAD

**Issue by musicEnfanthen** [rdfjs/N3.js#216]
Hi all,

first of all, thank you very much for this great library.

I use N3 in an Angular app (formerly Angular v8, now v10) to parse and visualize RDF input (see [1]). 

With Angular v8 everything worked fine, but after upgrading to Angular v10, the module that imported the N3 library in my application threw a ReferenceError (breaking the whole module). I was able to track down the issue to the use of N3, and finally the `stream` imports in the 

```
N3StreamWriter.js
N3StreamParser.js
N3Store.js
```
files. 

After a long search, I found out that replacing `stream` with `readable-stream` manually, as mentioned and explained here [2] and there [3] and over there [4], solved the issue.

I am not familiar enough with `stream` / `readable-stream` to foresee any side effects, but could you consider to accept a PR that changes the `stream` imports to `readable-stream` imports?

[1] https://edition.anton-webern.ch/edition/composition/op25/graph(side:editionInfo)
[2] https://github.com/DevExpress/devextreme-angular/issues/776#issuecomment-512766950
[3] https://www.nearform.com/blog/welcome-readable-stream-3/
[4] https://github.com/npm/are-we-there-yet/pull/2

**Comment by RubenVerborgh** [comment]
It seems like an angular problem to me, that would have unintended side-effects if I fixed it in N3.
What evidence do we have for it being an N3.js bug?

**Comment by musicEnfanthen** [comment]
Hi, thanks for your quick response.

> What evidence do we have for it being an N3.js bug?

Actually none, honestly. And I guess I would get the same answer from the Angular team considering it to be a N3 problem. ;) 

As I said, I am not familliar enough with `stream` to evaluate possible side effects, but from what I read, `stream` seems to be a more than 5 years old (dead? / unmaintained?) package. 

[readable-stream](https://www.npmjs.com/package/readable-stream) seems to mirror the streams implementations in Node.js and to "guarantee a stable streams base, regardless of what version of Node you, or the users of your libraries are using." 

In the [Usage section](https://www.npmjs.com/package/readable-stream#usage) it says:

> You can swap your require('stream') with require('readable-stream') without any changes, if you are just using one of the main classes and functions.

```
const {
  Readable,
  Writable,
  Transform,
  Duplex,
  pipeline,
  finished 
} = require('readable-stream')
```

As far as I can see this would be the case for N3?

May be more informed hints are given in this blog entry from 2014: https://r.va.gg/2014/06/why-i-dont-use-nodes-core-stream-module.html

**Comment by RubenVerborgh** [comment]
> Actually none, honestly. And I guess I would get the same answer from the Angular team considering it to be a N3 problem. ;)

So here's the thing: `stream` is built-in in Node, and N3.js is built for Node. So it is up to whatever thing that is compiling N3 for the browser to supply an adequate `stream` implementation. N3.js is currently being packed in many browser implementations, none of which have an issue… but they _might_ have, if I start using a non-default streaming library. Plus, module size could increase, etc. The new element here is Angular.

> `stream` seems to be a more than 5 years old (dead? / unmaintained?) package

It's not: we're using https://nodejs.org/api/stream.html (not https://www.npmjs.com/package/stream), which is as up-to-date as it gets.

https://www.npmjs.com/package/readable-stream on the other hand is already 6 months old.

Furthermore, it says that:

> > This package is a mirror of the streams implementations in Node.js.

Which is exactly what I'm using so… yeah, I really think it is Angular.

I appreciate the pointers, but 6 years old is prehistoric on a JS timescale 🙂

**Comment by RubenVerborgh** [comment]
Can you perhaps tweak Angular packing settings? At least with webpack, it's possible to replace any module at compile time, so you could say you want `readable-streams` instead of `streams`.

**Comment by ktk** [comment]
This issue was raised before, see [here](https://github.com/rdfjs/N3.js/issues/159). The easy fix is to switch from `stream` to `readable-stream`. It would make no difference from a node POV but fixes issues in browser environments.

We have people stumbling over this issue [on a regular base](https://gitter.im/rdf-ext/discussions?at=5c2f77658dafa715c73f89f9), our clients have it as well, mostly in Angular-env which is quite common in companies.

We use `readable-stream` everywhere and it works great.

**Comment by RubenVerborgh** [comment]
I’m willing to consider it, **but** someone should tell me what the exact problem is, i.e., why precisely Angular (and what others) trip over this.

**Comment by RubenVerborgh** [comment]
Also, the arguments of #159 have changed: we have tree shaking now, so the fact that we only need a small subset is no longer relevant.

I will probably change this (curious about @rubensworks though), but I still want to fully get the problem. Already convinced about the solution nonetheless.

**Comment by bergos** [comment]
`stream` is a package provided by the Node.js environment. An environment that strictly says it supports only CommonJS or ESM, doesn't know about `stream`. The Webpack default config gives you an environment with `stream`, the environment of Angular is not aware of any packages besides the ones available from npm. As far as I understood, this is done via a custom Webpack config. I can understand both sides, but I'm not happy how Angular did it. Usually, I would expect a deprecated message as a first step. Anyway, people are stumbling over it now and it should be fixed.

Besides the Angular problem is see two more arguments for using `readable-stream`:

- If only npm packages are used, there is a higher chance that this package will also work on other environments. Devices, databases, ... everyone nowadays has built-in JS support. Not having a `stream` package should be not a reason against using RDF.
- The argument in the old issue is still valid: If you use the stream from a package defined in the dependencies, you know what you get. Node.js had only in earlier versions breaking changes, but semantic versioning would allow them to have breaking changes with every major version. It could be also the other direction if someone uses an old version of Webpack with an old version of `readable-stream`, which causes somehow problems with your package. The obvious solution would be upgrading Webpack, but with the right version enforced with dependencies you may save some round trips here on the issue tracker.

**Comment by rubensworks** [comment]
Indeed, it looks like Angular decided to only work with browser-specific JS as of version 6.x: https://github.com/angular/angular-cli/issues/9827#issuecomment-369578814
I don't think we have any leverage in requesting Angular to change this,
so migrating to `readable-stream` might be the best way forward here.

**Comment by RubenVerborgh** [comment]
Thanks @musicEnfanthen, @ktk, @bergos, @rubensworks. Will be released as v1.6.2.

**Comment by musicEnfanthen** [comment]
Hi all,

thanks a lot for your additional input, discussion and arguments, and thanks @RubenVerborgh for the quick reaction and fix!

**Comment by inukshuk** [comment]
Just to belatedly offer a contrarian view to this, the switch to `readable-stream` causes issues for people using Rollup, creating bundles for a Node.js environment.

Using `stream` there are no additional dependencies to worry about at all. When using `readable-stream`, however, not only do we need to include this in the bundle, but there are all kinds of issues bundling `readable-stream` with Rollup. True, there [seem to be solutions for this](https://github.com/rollup/plugins/issues/545), which, at least in my case, cause all kinds of additional headaches. Having spent a few hours on this, I realized that the easiest solution is to patch this library, replacing `readable-stream` with `stream`.

I understand that depending on `stream` seems to cause bundling issues in other scenarios; but I just wanted to mention that the reverse is also true.

**Comment by RubenVerborgh** [comment]
Thanks for sharing this, @inukshuk, and sorry to hear that. Doesn't rollup offer simple library replacements like webpack does?

But in any case, good to have this documented.

**Comment by inukshuk** [comment]
As a caveat, I'm only just starting out with Rollup so I easily might have missed a better solution (still, there is no shortage of Rollup / readable-stream related issues here on GitHub). What I do now is probably very similar to what webpack would do if it replaces libraries, since I'm just swapping the imports prior to loading the modules (using `@rollup/plugin-replace` in case this is helpful to anyone).
