### ISSUE TITLE
Could not find module in path: 'readable-stream/errors' relative to '/node_modules/readable-stream/lib/internal/streams/state.js'

### ISSUE THREAD

**Issue by Vinnl** [rdfjs/N3.js#217]
I'm not sure whether this error is limited to CodeSandbox, but fce997bbba14b9f30c5d93c54d80d4c430eb37cb (i.e. v1.6.2) breaks it:

- [CodeSandbox importing from 1.6.1](https://codesandbox.io/s/beautiful-https-9ufrz?file=/src/App.js:27-48)
- [CodeSandbox importing from 1.6.2](https://codesandbox.io/s/white-http-3xnmt?file=/src/App.js:27-48)

(On the left-hand side you can see the selected version of the dependency. I'm using the default React template, only adding `import {} from "n3";`.)

(Related: https://github.com/rdfjs/N3.js/issues/216#issuecomment-672859174)

**Comment by RubenVerborgh** [comment]
Must be limited to CodeSandbox; follows from #216. @bergos Do you have insights by any chance?

**Comment by bergos** [comment]
I haven't used CodeSandbox before, so I don't know exactly what's going on behind the scenes. I tried to import just `readable-stream/errors.js` and I also got the `ModuleNotFoundError`. I check if the file is in the distributed package, not just in the git repo, and found the file [errors.js](https://unpkg.com/readable-stream@3.6.0/errors.js) with unpkg.

Could it be some incomplete cached install problem? Is it somehow possible to clear the cache and reinstall the dependencies? For further analyses, it would be good to see all installed dependencies + versions or even better have access to files in the installed dependencies. Is that somehow possible?

**Comment by Vinnl** [comment]
Not that I'm aware of, though I'm not intimately familiar with CodeSandbox either. Interestingly, directly importing from readable-stream _does_ work: https://codesandbox.io/s/cocky-curie-jh39d?file=/src/App.js:27-60

**Comment by Vinnl** [comment]
Ah, and weirdly enough, if I have both readable-stream and n3 as a dependency, it does work: https://codesandbox.io/s/confident-kalam-3xxij?file=/src/App.js:27-47

So I suppose that at least serves as a workaround for CodeSandbox users. Would be interesting to see if people run into this in other environments as well.
