### ISSUE TITLE
gh-pages documentation is not up to date

### ISSUE THREAD

**Issue by bourgeoa** [rdfjs/N3.js#220]
The last documentation dates back 23, April 2018 is outdated and do not list all public functions.
For example `removeMatches` `removeGraph` are not listed.

in .travis_build_pages : REPO_NAME="RubenVerborgh/N3.js" I suppose it should be `"rdfjs/N3.js"`

**Comment by RubenVerborgh** [comment]
Woops, thanks for spotting this.

**Comment by bourgeoa** [comment]
It is still not working we got a 404 page.
Could it be that the github.io location is not the new one ?

**Comment by RubenVerborgh** [comment]
Should be better after 964313d25e186dc06c1a45ba6f2a382b7c377238, with http://rdf.js.org/N3.js/docs/ and http://rdf.js.org/N3.js/docs/N3Lexer.html
