### ISSUE TITLE
How to add escape sequence in literal

### ISSUE THREAD

**Issue by pheyvaer** [rdfjs/N3.js#221]
Hi,

I want to add `\t` as a literal, i.e., have literal `"\t"`. But when I create literal via this library I get `"\\t"`. Is there a way to avoid this?

**Comment by pheyvaer** [comment]
The code that we use is

```
const {DataFactory} = require('n3');
const {namedNode, literal, quad} = DataFactory;

const literal = literal('\t');
```

The intention is indeed to have a literal with a tab character.

**Comment by RubenVerborgh** [comment]
I confirm that the above code creates a literal consisting of a tab character.

So what is the issue? 🙂

**Comment by pheyvaer** [comment]
I was incomplete in my initial issue: afterwards I use the Writer to generate the Turtle and there I get `"\\t"`.

**Comment by RubenVerborgh** [comment]
Cannot reproduce:

```javascript
const l = literal('\t');
const n = namedNode('http://e.example/');
const writer = new Writer();
writer.addQuad(n, n, l);
writer.end((error, data) => console.log(data));
```

gives

```turtle
<http://e.example/> <http://e.example/> "\t".
```

**Comment by RubenVerborgh** [comment]
You're not using `JSON.serialize` anywhere, are you? 😉

**Comment by pheyvaer** [comment]
Not I'm not, but will check again my use case and see if I missed something!

**Comment by RubenVerborgh** [comment]
Let me know if it surfaces.
