### ISSUE TITLE
Prefixed Resources that start with a dash cause a parsing error

### ISSUE THREAD

**Issue by Vinnl** [rdfjs/N3.js#224]
When a subject starts with a `-` after the prefix, n3 throws an error:

To reproduce:

```
const n3 = require("n3")

const turtle = `
@prefix : <#>.
@prefix ldp: <http://www.w3.org/ns/ldp#>.

:-dash-
    a ldp:Resource.
`;

const parser = new n3.Parser({
  format: "text/turtle",
  baseIri: "https://example.com/resource"
});

parser.parse(turtle, (error, triple) => {
  if (error) {
    console.log("This should not error, but it does:", error);
  }
});
```

Output:

> Error: Unexpected ":-dash-" on line 5.

(Unfortunately I could not properly share the code directly on RunKit, but if you copy-paste the above code here, you should be able to see it: https://npm.runkit.com/n3)

I think the above is valid Turtle, but apologies if it is not.

**Comment by RubenVerborgh** [comment]
It's invalid Turtle, so the behavior is correct and needed: https://www.w3.org/TR/turtle/#grammar-production-PrefixedName
