### ISSUE TITLE
Modernize Code Base

### ISSUE THREAD

**Issue by dhurlburtusa** [rdfjs/N3.js#227]
I am wondering if you would like to "modernize" the code base. I thought maybe you would based on wanting to switch to arrow functions in some places in the code base. But maybe that change was more motivated by not wanting to create closures to some of the class's members.

I was thinking of just changing `var`s to `const`s or `let`s. I don't know what the performance implications are since I've never profiled or benchmarked this particular change. I can't imagine there being any.

Thoughts?

Any other changes you may be interested in? I assume we want to continue supporting Node.js v8.0 or newer based on the condition in package.json under engines.

**Comment by dhurlburtusa** [comment]
@RubenVerborgh May I get an explanation why you closed this issue? That is, why don't you want to switch to using `const`s and `let`s? Are there some performance implications I am not aware of? Some other reason(s)?

**Comment by RubenVerborgh** [comment]
I closed it because I did it 🙂 Thanks for the suggestion!

https://github.com/rdfjs/N3.js/commit/d9c40869b0f00d29fdbba74cc142b0da22601d53
