### ISSUE TITLE
Add RDF.js Dataset interface to N3.Store?

### ISSUE THREAD

**Issue by Jamie-SA** [rdfjs/N3.js#237]
Some Javascript libraries (like rdf-validate-shacl) now accept and return RDF.js Datasets but I don't think they will work with N3.Store. I am wondering about adding the Dataset interface either to the N3.Store or a wrapper that would make it look like a Dataset.

Have you already decided that is a bad idea? Are you interested in including that?

**Comment by RubenVerborgh** [comment]
> Have you already decided that is a bad idea?

Good idea!

> Are you interested in including that?

Yes, but no bandwidth on my side, currently. But I'd gladly accept PRs, or [funding](https://github.com/sponsors/RubenVerborgh) such that I can have a student work on it.

**Comment by Jamie-SA** [comment]
Cool! We will submit a PR.
Do you have a preference for how it is added, in the main Store code or more as a wrapper?

**Comment by RubenVerborgh** [comment]
If a wrapper, then this is a general tool that could be used for all RDF.js datasets. That would be interesting.

However, I think that you'll want the internal store access for performance.

**Comment by Jamie-SA** [comment]
@dhurlburtusa has been looking into this for us. One of our drivers is to be able to use rdf-validate-shacl. It looks like it only requires the DatasetCore interface so we will probably focus on that first.

There does seem to be an interface conflict, both N3.Store and DatasetCore have match() with identical parameter signatures but different return types, a DatasetCore for RDF.js and a Stream for N3.Store. Any good ideas how to deal with that? I've got a couple ideas but they are a little clunky so open to options.

**Comment by RubenVerborgh** [comment]
> identical parameter signatures but different return types, a DatasetCore for RDF.js and a Stream for N3.Store. Any good ideas how to deal with that?

Return a hybrid object that implements both interfaces? Streams are lazy anyway.

**Comment by dhurlburtusa** [comment]
@RubenVerborgh A PR (#240) has been made to implement this functionality.

**Comment by pmcb55** [comment]
@dhurlburtusa @Jamie-SA - this is really great to see (the more performant spec-compliant RDF/JS DatasetCore/Dataset implementations the better). But can I ask if you investigated using Graphy first, especifically it's faster-than-N3 Dataset implementation [@graphy/memory.dataset.fast](https://www.npmjs.com/package/@graphy/memory.dataset.fast)...? Did you try it and find it unsuitable in any way...?

**Comment by Jamie-SA** [comment]
@RubenVerborgh I think you merged the code to address this issue. Closing.

**Comment by RubenVerborgh** [comment]
Indeed, thank you!
