### ISSUE TITLE
Issue when converting boolean literal from quads to a string

### ISSUE THREAD

**Issue by marcelomachado** [rdfjs/N3.js#239]
I am converting quads stored in a `N3.Writter` object to string. However, one of my statements contains a boolean literal object, e.g.: 

```
literal(
  true,
  namedNode("http://www.w3.org/2001/XMLSchema#boolean")
)
```

When I use the `end` function of the  `N3.Writter` instance, it converts my quads to an rdf serialization (I am using TriG - `application/trig`), but it does not insert the boolean literal type. Since there is more than one statement in my object the parser put a `.` at the end of each statement without any space(` `). It is a problem for some Triplestores.

At a glance, this is the result:
```
<http://xxx/yyy#context> {
<http://xxx/yyy#acde45001121> <http://xxx/yyy#property> true. # no-space
<http://xxx/yyy#acde45001121> a <http://xxx/yyy/graph#test>
} 
```
It should be:
```
<http://xxx/yyy#acde45001121> {
<http://xxx/yyy#acde45001121> <http://xxx/yyy#property> true . # with space
<http://xxx/yyy#acde45001121> a <http://xxx/yyy/graph#test>
} 
```
or

```
<http://xxx/yyy#acde45001121> {
<http://xxx/yyy#acde45001121> <http://xxx/yyy#property> "true"^^<http://www.w3.org/2001/XMLSchema#boolean>. # no need for space since it contains the data type
<http://xxx/yyy#acde45001121> a <http://xxx/yyy/graph#test>
} 
```

**Comment by RubenVerborgh** [comment]
> It is a problem for some Triplestores.

They don't follow the spec though: https://www.w3.org/TR/turtle/#sec-grammar

So I'm afraid you'll need to file a bug with those triple stores.

Alternatively, you can serialize to N-Quads, which does not use the abbreviated notation.
