### ISSUE TITLE
How can I list quads from Store where subject and predicate are identical over all quads?

### ISSUE THREAD

**Issue by Falx** [rdfjs/N3.js#250]
Hi,

I have a use case where I am reading in a webId with the Parser. This contains blankNodes and lists for acl and I want to write it back in a syntactic similar form (using `[]` and `()` ). The Parser will have changed the blankNodes to a blankNodePrefixed form and write the list entries as separate Quads. 

Now I want to go through the quads and filter for instance all quads that have a identical subject and predicate (identical to the other quads that is). This would allow me to then reconstitute the lists by grouping the values and doing the correct calls to `Writer.list()`.

So now for my question: how can I use the `Store.match()` function to get all quads where subject and predicate are equivalent, without actually putting in a literal value? 
I tried with `variable()` but that didn't get me any results.

**Comment by rubensworks** [comment]
`Store.match()` will not do any cross-term comparison, so this is something that has to be done manually as a post-processing step.

> This would allow me to then reconstitute the lists by grouping the values and doing the correct calls to Writer.list().

This doesn't sounds strictly necessary, as `Writer.list()` is just for pretty-printing. Just pushing/streaming the new quads directly will get you isomorphic output.

If you're interacting with a Solid server, you may also be able to just do a [SPARQL Update patch](https://github.com/solid/solid-spec/blob/master/api-rest.md#alternative-using-sparql-1), and let the server take care of pretty-printing.
