### ISSUE TITLE
`quadToString` always returns N-Quads or N-Triples

### ISSUE THREAD

**Issue by LaurensRietveld** [rdfjs/N3.js#253]
The `writer.quadToString()` [function](https://github.com/rdfjs/N3.js/blob/ddf9f45516349f0dcf7c62f41bbcd94016e3e49e/src/N3Writer.js#L120) always returns N-Quads or N-Triples, regardless of format that's passed to the writer constructor.

I wrongly expected the `format` constructor argument to define the serializations returned by member functions such as `quadToString`.

Not sure whether this is something the solve via documentation or by changing the JS API

**Comment by RubenVerborgh** [comment]
Hmm, these are supposed to be private methods; the real bug is that they don't start with an underscore.
I take it you have code relying on this?

**Comment by LaurensRietveld** [comment]
> Hmm, these are supposed to be private methods; the real bug is that they don't start with an underscore.

And, another bug is that the interface is typed in the typescript definition giving the developer an intuition that it's public: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/ec76f9ae7f670dbcee3ca06d0ba55caa9bfa8768/types/n3/index.d.ts#L211
I'll make a PR to remove those typings

> I take it you have code relying on this?

I dont recall tbh, but fine if you assume we're not ;)

**Comment by RubenVerborgh** [comment]
> I'll make a PR to remove those typings

Super, thank you!
