### ISSUE TITLE
[Enhancement] [Types] Stricter types using template literals

### ISSUE THREAD

**Issue by jeswr** [rdfjs/N3.js#255]
Now that [typescript supports template literals](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-1.html) it may be worthwhile making the options parameters in DefintelyTyped more strict?

For instance the format argument in `ParserOptions`

```ts
type BaseFormat = 'turtle' | 'trig' | 'triple' | 'quad' | 'n3'
type Star = 'star' | '*'
type Format = `${BaseFormat}${Star}`
```

**Comment by rubensworks** [comment]
Agreed! Perfect use case for this.

**Comment by TallTed** [comment]
This may have been merged too quickly...

Note that the RDF-star CG has settled on `-star` as the suffix for both the data model and the adjusted serializations (e.g., RDF-star, Turtle-star) -- which include some but perhaps not all formats your code expands to -- all of which is still in a draft-CG-report, so support for these serializations may be premature -- and your "stricter" types do not in fact appear to be "stricter" (as `Turtle*`, `Turtlestar`, and `Turtle-star` make one type look like three, to me).

**Comment by RubenVerborgh** [comment]
As far as I can see, all works as expected, which is:
- full MIME types are accepted
- shorthands such as "Turtle" are accepted

**Comment by TallTed** [comment]
It is *possible*, but I would say we're 1–3 years from even the possibility, that "Turtle-star" may be adopted as the next version of Turtle — and until then, "Turtle" is not the same as what is currently (and may continue to be) known as "Turtle-star", nor is "Turtle" a shorthand; "Turtle" is the proper name for the serialization with media type `text/turtle`.

"Turtle" is just an example.  Each serialization and its media types should be addressed in its own right.
