### ISSUE TITLE
global is not defined

### ISSUE THREAD

**Issue by NoelDeMartin** [rdfjs/N3.js#257]
I've tried using the library with [vite](https://vitejs.dev/) and I think it's very close to work out of the box, because I only get this error and once I add the following to my html it works:

```html
<script>window.global = window</script>
```

I'm not sure how easy it is to fix this within the library, and sorry if it has been discussed before, but I didn't find any reference to this in particular. In the README it mentions that it should work with webpack, but as far as I know this problem would happen with webpack 5 as well (I haven't tried though).

In case you need a reproduction, here it is: https://github.com/NoelDeMartin/vite-sandbox/tree/n3

**Comment by NoelDeMartin** [comment]
> Did yours work for "npm run build" too?

Yes, it worked both for development and production. Make sure that you're adding the `window.global = window` script before any other script though, maybe that's the issue.

I haven't seen that error from `queue-microtasks`, although I'm also using n3 through another library and not directly. I'm using it from [@noeldemartin/solid-utils](https://github.com/NoelDeMartin/solid-utils), but I also use it from [soukai-solid](https://github.com/noeldemartin/soukai-solid) and I'm using [a different solution there](https://github.com/NoelDeMartin/soukai-solid/blob/next/src/solid/external.ts#L6).

I am a bit lost as to why this is an issue though, I'd appreciate some guidance from the maintainers.

**Comment by KonradHoeffner** [comment]
I think it has something to do with the library being designed for Node.js and not for the browser, however I don't know how to solve this issue.

**Comment by RubenVerborgh** [comment]
> I've tried using the library with [vite](https://vitejs.dev/) and I think it's very close to work out of the box, because I only get this error and once I add the following to my html it works:

I'm a bit puzzled though; I don't find any occurrences of `global`. Moreover…

> In case you need a reproduction, here it is: https://github.com/NoelDeMartin/vite-sandbox/tree/n3

It seems to be fixed now. Perhaps some libraries have been updated in the meantime?

**Comment by NoelDeMartin** [comment]
> It seems to be fixed now. Perhaps some libraries have been updated in the meantime?

@RubenVerborgh How did you try it? I just noticed that it works doing a build, but it fails if you run it with `npm run dev`. I'm also quite lost as to why this happens :/.

**Comment by RubenVerborgh** [comment]
It's a Vite bug/feature.

The bug is https://github.com/vitejs/vite/issues/2778#issuecomment-810086159
and resolution that worked for me is https://github.com/bevacqua/dragula/issues/602#issuecomment-912863804
