### ISSUE TITLE
N3Parser should allow literal subjects

### ISSUE THREAD

**Issue by tibotiber** [rdfjs/N3.js#26]
Hi Ruben,

It seems that the store accepts literals only for objects, it will refuse them for subjects right? This made my application crash when loading the store with triples parsed from EYE inference results using the following rule.

```
{?P rdfs:range ?C. ?X ?P ?Y} => {?Y a ?C}.
```

I have solved it by modifying the rule to

```
{?P rdfs:range ?C. ?X ?P ?Y. ?Y log:rawType ?T. ?T owl:differentFrom rdfs:Literal} => {?Y a ?C}.
```

I was wondering whether it would be better to make the store more permissive on this aspect. What do you think?

Thibaut.

**Comment by RubenVerborgh** [comment]
This has been supported for some time now.
