### ISSUE TITLE
Why Turtle writer doesn't write `@base` directive?

### ISSUE THREAD

**Issue by EgorKluch** [rdfjs/N3.js#264]
I create writer with `baseIRI` option.

```
const writer = new Writer({
    format: 'Turtle',
    baseIRI: 'https://example.com/',
    prefixes: {
      ...reservedPrefixes,
      ...data.prefixes,
    },
  });
```

But, `@base` directive wasn't add. However, urls was truncated. And I can't find how I can add `@base` directive in documentaion and in `Writer` code.

Please, help. Why it's not implemented, what I don't understand?

![image](https://user-images.githubusercontent.com/2197074/143379798-9b22d1a0-1827-4ed9-ac7a-bb543db09315.png)

**Comment by EgorKluch** [comment]
I use `writer._write` to decide this problem. It's terrible hack(

But I can do pull request with fix, when I will understand reasons why `@base` directive wasn't implemented.

**Comment by RubenVerborgh** [comment]
The `baseIRI` directive is for when you want to host the document at a certain location, not for `@base`.
I can accept a pull request for `@base` indeed, but as an additional option/flag.

**Comment by ManuelTS** [comment]
Still having the issue that the Writer does not write `@base`

**Comment by RubenVerborgh** [comment]
The `baseIRI` directive is for when you want to host the document at a certain location, not for `@base`.
I can accept a pull request for `@base` indeed, but as an additional option/flag.
