### ISSUE TITLE
Make NamedNode compare under Immutable.js

### ISSUE THREAD

**Issue by drewp** [rdfjs/N3.js#265]
```
    "immutable": "^4.0.0",
    "n3": "^1.11.2",
    "@types/n3": "^1.10.4",

    const x = new NamedNode("x");
    const x2 = new NamedNode("x");
    expect(x === x2).toBeFalsy();
    expect(x == x2).toBeFalsy();
    expect(x.equals(x2)).toBeTruthy();

    let imap = Immutable.Map();
    imap = imap.set(x, 11);
    imap = imap.set(x, 22);
    imap = imap.set(x2, 33);
    expect(imap.has(x)).toBeTruthy();
    expect(imap.has(x2)).toBeTruthy();
    expect(imap.size).toEqual(1); // fails: size is 2
```

Here's a fix:
```
(NamedNode.prototype as any).hashCode = () => 0;
```

Please consider adding some hashCode function with the usual hash rules to NamedNode (or Term?). Immutable.js [wants it to be in the range of uint32](https://immutable-js.com/docs/v4.0.0/ValueObject/#hashCode()).

**Comment by RubenVerborgh** [comment]
Right; it hadn't occurred to me that the `.equals` would be picked up by Immutable.js.

**Comment by RubenVerborgh** [comment]
@rubensworks Surprised you never hit this.

**Comment by AlexeyMz** [comment]
Hi. Is it really a good idea to implement `hashCode()` this way? I think without hash function with good distribution Immutable.js collections will perform poorly, O(N) instead of O(log N) or worse.

It is possible to implement a good hash function for RDF/JS terms like this: https://github.com/ramp-shapes/ramp-shapes/blob/master/src/rdf/rdf-model.ts

**Comment by RubenVerborgh** [comment]
@AlexeyMz It's just minimal implementation that does not break Immutable.js. More optimal implementations are possible, but they increase client code size, and are not a priority for this library. Plus it is possible to use another factory with N3.js.

**Comment by drewp** [comment]
Indeed, this one takes my project from not-working to working, and I have datasets of like 60 statements so I don't care (yet). 

BTW, I wanted URIs and pairs of URIs as map keys. That's the only reason I added Immutable. Are there other Map-like and Set-like libs that would work?

**Comment by RubenVerborgh** [comment]
> I wanted URIs and pairs of URIs as map keys.

That might also work with strings and concatenated strings (separated by a non-IRI character like `*`).

> Are there other Map-like and Set-like libs that would work?

Standard map/set with string keys above.

**Comment by AlexeyMz** [comment]
@drewp You can also take a look at simple hash map/set implementation like this: https://github.com/ramp-shapes/ramp-shapes/blob/master/src/hash-map.ts

**Comment by drewp** [comment]
Still breaking here. https://immutable-js.com/docs/v4.0.0/ValueObject/#hashCode() wants a method, not a getter. 

They check for `typeof v.hashCode === 'function'` (https://github.com/immutable-js/immutable-js/blob/main/src/predicates/isValueObject.js)

**Comment by RubenVerborgh** [comment]
Thanks, done in 088006449c9e8275351db604b3d184071fef31a7.
