### ISSUE TITLE
Writer.quadsToString() doesn't parse numeric literals correctly

### ISSUE THREAD

**Issue by jaxoncreed** [rdfjs/N3.js#269]
Hey everyone, I'm having trouble with using n3 to make N-Triples.

In the following code:

```typescript
import { Parser, Writer } from "n3";

const turtle = `
  @prefix example: <http://example.com/> .
  example:aang
    example:age 12 .
`;
// Parse Turtle
const parser = new Parser({ format: "text/turtle" });
const quads = parser.parse(turtle);
const writer = new Writer();
const stringRepresentation = writer.quadsToString(quads);
console.log(stringRepresentation);
```

The result is:

```
<http://example.com/aang> <http://example.com/age> 12 .
```

The correct N-Triple should be either

```
<http://example.com/aang> <http://example.com/age> "12"^^<http://www.w3.org/2001/XMLSchema#integer> .
```

or 
```
<http://example.com/aang> <http://example.com/age> "12" .
```

Literals in n3 must be surrounded by quotes. See the [N-Triples spec](https://www.w3.org/TR/n-triples/#sec-literals)

> The representation of the lexical form consists of an initial delimiter " (U+0022), a sequence of permitted characters or numeric escape sequence or string escape sequence, and a final delimiter.

**Comment by joachimvh** [comment]
The writer defaults to turtle if you don't provide a format, where `12` is valid. If in your example you change to `const writer = new Writer({ format: 'application/n-triples' });` you will get the output you mention.

**Comment by jaxoncreed** [comment]
Ah dope. Thanks.
