### ISSUE TITLE
Performance: Asynchronously retrieve data with `_read`

### ISSUE THREAD

**Issue by jeswr** [rdfjs/N3.js#274]
Currently, the implementation of `_read` means that all `matches` are stored in an array before we can iterate over the matches in a stream. This has drawbacks for both space and performance.

Instead, it would be good to have an implementation that retrieves that data directly from the index with `_read` is called.

I would also note that `has` would see significant performance improvements from such changes.

Note the only potential drawback is that the results set may change if users add data at the same time while they are streaming data using `match`.

**Comment by jeswr** [comment]
> Wait, is Comunica really using N3Store?

Turns out internally no - but I'd imagine it is used as a `source` by many applications. Furthermore; I was using it as the default to store implicit data in the reasoning extension for Comunica (though perhaps I should look into other options like graphy and quadstore as well to see what their streaming benchmarks are like)

**Comment by rubensworks** [comment]
Comunica actually does use n3store, when querying over files.
