### ISSUE TITLE
Feat: Extract `EntityIndex` class

### ISSUE THREAD

**Issue by jeswr** [rdfjs/N3.js#289]
Would look something like

```ts
import { default as N3DataFactory, termToId, termFromId } from './N3DataFactory';

type Term = any;

interface EntityIndex<ID, T extends Term = Term> {
  termToId(term: Term): ID | undefined;
  termToIdSafe(term: Term): ID;
  idToTerm(id: ID): T | undefined;
}

class N3EntityIndex implements EntityIndex<number> {
  private ids: Record<number, Term> = {};
  private entities: Record<Term, number> = {};
  private id = 0;
  private factory;

  termToId(term: Term): number | undefined {
    term = termToId(term);
    return this.entities[termToId(term)];
  }

  termToIdSafe(term: Term): number | undefined {
    term = termToId(term);
    return this.entities[term] || (this.ids[this.entities[++this.id] = term]   = this.id);
  }

  idToTerm(id: number): Term {
    return termFromId(this.ids[id], this.factory);
  }
}
```

The point of this is to enable multiple sources to share the same `EntityIndex` for memory/performance reasons.

Pinging @jacoscaz who may have already done something similar with scoping in quadstore.

**Comment by rubensworks** [comment]
A big 👍 from me on this.
Would be crucial for things like https://github.com/comunica/comunica/issues/873.

An alternative approach could be to store this `id` value within the RDF/JS `Term`, but not sure which approach would be more convenient.

**Comment by jeswr** [comment]
> allternative approach could be to store this id value within the RDF/JS Term

My main concern with this approach would be having to handle conflicting ID's if there are multiple sources.

**Comment by rubensworks** [comment]
> My main concern with this approach would be having to handle conflicting ID's if there are multiple sources.

Indeed, we'll need a way of detecting distinct sources if we'd go this route (not saying we should). (I did something similar to that here: https://rdfostrich.github.io/article-jws2018-ostrich/#dictionary)

**Comment by jeswr** [comment]
Implemented in https://github.com/rdfjs/N3.js/pull/394
