### ISSUE TITLE
DataFactory tests for Triple and Quad insinuate unquoted literals are acceptable

### ISSUE THREAD

**Issue by rorlic** [rdfjs/N3.js#305]
The [Triple and Quads](https://github.com/rdfjs/N3.js/blob/main/test/N3DataFactory-test.js#L103) tests in the DataFactory tests use literals without double-quotes insinuated that a Literal can be created as follows:
```javascript
new Literal('abc')
```
however the Literal `value` is defined as:
```javascript
  // ### The text value of this literal
  get value() {
    return this.id.substring(1, this.id.lastIndexOf('"'));
  }
```
which will return `a` as the `value`, not `abc`:
A simple test proves that:
```javascript
  describe('A literal value without quotes', () => {
    it('should equal that value', () => {
      new Literal('abc').value.should.be.equal('abc');
    })
  })
```
results in:
```
  1542 passing (950ms)
  1 failing

  1) Literal
       A literal value without quotes
         should equal that value:

      AssertionError: expected 'a' to equal 'abc'
      + expected - actual

      -a
      +abc
      
      at Context.<anonymous> (test/Literal-test.js:644:42)
      at processImmediate (node:internal/timers:471:21)
```

Can I assume that the tests are wrong and should all contain literals as follows?
```javascript
new Literal('"abc"')
```
Or can a `Literal` be created as an unquoted string, and is the `value` implementation not correct?

**Comment by RubenVerborgh** [comment]
> The [Triple and Quads](https://github.com/rdfjs/N3.js/blob/main/test/N3DataFactory-test.js#L103) tests in the DataFactory tests use literals without double-quotes insinuated that a Literal can be created as follows:
> 
> ```js
> new Literal('abc')
> ```

This is an internal data structure that is not exposed; the `dataFactory` interface should be used, which exposes `.literal`.
