### ISSUE TITLE
New release for better browser support

### ISSUE THREAD

**Issue by bergos** [rdfjs/N3.js#309]
The latest version of `readable-stream` doesn't require any polyfills for browser builds. See [this PR](https://github.com/nodejs/readable-stream/pull/489). The dependency in N3 was already updated in [this commit](https://github.com/rdfjs/N3.js/commit/e531951ac7f3ec085fb7faab8f1d746a0f8c2fef), but there is no new release yet. It would be great if a new version could be published on npm.

**Comment by RubenVerborgh** [comment]
Released as v1.16.3!
