### ISSUE TITLE
Implement DatasetCoreFactory

### ISSUE THREAD

**Issue by RubenVerborgh** [rdfjs/N3.js#314]
We should implement the [DatasetCoreFactory](https://rdf.js.org/dataset-spec/#datasetcorefactory-interface);
an example implementation is here: https://github.com/iherman/rdfjs-c14n/blob/3d87b3a8e0513329057c19ff707f0e4bb835c0cc/testing/run/rdfn3.ts#L17-L26

**Comment by jeswr** [comment]
https://github.com/rdfjs/N3.js/pull/288 does a fair bit of that work
