### ISSUE TITLE
`npm ci` fails on node 14 when package build in node 19 includes `n3` dependency

### ISSUE THREAD

**Issue by jeswr** [rdfjs/N3.js#317]
To reproduce run `nvm use 19 && npm init -y && npm i n3 && nvm use 14 && npm ci`. The final `npm ci` command results in the error

```
npm ERR! Cannot read property 'n3' of undefined

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/jesse/.npm/_logs/2022-12-29T02_17_59_834Z-debug.log
```

**Comment by jeswr** [comment]
The exact versions that this uses on my machine are

```
v19.3.0 (npm v9.2.0)
v14.20.0 (npm v6.14.17)
```

**Comment by RubenVerborgh** [comment]
Was it https://github.com/rdfjs/N3.js/issues/310 by any chance?

**Comment by jeswr** [comment]
Ah nevermind; this is not a problem specific to `n3` (the same happens with any other package I try, such as `is-even`).
