### ISSUE TITLE
IRI fragments cannot start with a digit

### ISSUE THREAD

**Issue by twalmsley** [rdfjs/N3.js#325]
I'm using random UUIDs after the `#` in IRIs and some of them start with digits, but the prefix replacement regex doesn't match these IRIs. Is there a reason for that or is it a bug? I can't find anything in the W3C that restricts fragments in this way.

E.g. `https://www.example.com/test/things#3add0a26-8c75-47fb-abe7-a0ed1c23a0a` doesn't match the generated regex:
`^(?:hqdm:|amrc:|rdf:)[^/]*$|^(https:\/\/www\.example\.com\/test\/things#)([_a-zA-Z][\-_a-zA-Z0-9]*)$`

The result is that some IRIs are not shortened using a prefix when exported (to TLL in my case), although the TTL is still valid.

**Comment by RubenVerborgh** [comment]
That's by design indeed; the Writer prefixes _some_ URIs, but not all of them. The regex can be expanded indeed, but getting it perfect for all cases would make it slow. That said, yours is a reasonable case that I wouldn't expect to slow down things.
