### ISSUE TITLE
Any way to recover from unescaped double quotes?

### ISSUE THREAD

**Issue by excursus** [rdfjs/N3.js#350]
The  2022-03 snapshot of dbpedia contains iris with unescaped double quotes such as this one:
```
<http://dbpedia.org/resource/"populate_or_perish"> <http://www.w3.org/2002/07/owl#sameAs> <http://rdf.freebase.com/ns/m.01182wk6> .
```
see [here](https://dbpedia.org/sparql?default-graph-uri=http%3A%2F%2Fdbpedia.org&query=select+*+where+%7B%0D%0A%3Fs+%3Fp+%3Chttp%3A%2F%2Frdf.freebase.com%2Fns%2Fm.01182wk6%3E.%0D%0A%7D+LIMIT+100&format=text%2Fhtml&timeout=30000&signal_void=on&signal_unconnected=on). This causes the lexer to throw this error:
```
    const err = new Error(`Unexpected "${issue}" on line ${this._line}.`);
                ^
Error: Unexpected "<http://dbpedia.org/resource/"populate_or_perish">" on line 820.
```
Is there any way to gracefully recover from errors such as these?

**Comment by jeswr** [comment]
No there is not, N3.js is designed to throw errors on invalid syntax as is the case with these IRIs (note that the definition of IRIREF explicitly forbids them in the [production grammar](https://www.w3.org/TR/turtle/#sec-grammar-grammar)).

I suggest you raise an issue with the DBPedia team to request they remove such invalid IRIs from their dataset.

**Comment by TallTed** [comment]
@excursus — I believe the [DBpedia Information Extraction Framework](https://github.com/dbpedia/extraction-framework/issues) is the best repository for issues such as this. If not, they should be able to point you in a better direction.
