### ISSUE TITLE
Usage of `import` as method names

### ISSUE THREAD

**Issue by martines3000** [rdfjs/N3.js#380]
Hi. We are developing a project that is running inside a hardened JavaScript environment called [SES](https://github.com/endojs/endo/tree/master/packages/ses) (Secure EcmaScript) and this library is one of our sub-dependencies. SES doesn't allow overriding “reserved” keywords like `import` and this causes many issues for us.

My question is if it would be possible to maybe rename methods like this:
https://github.com/rdfjs/N3.js/blob/51a41564467252278f4b8b5998453ad88f607ced/src/N3Store.js#L305
from `import(stream)` to something like `_import(stream)`. This would solve our problems.

Thank you for the help.

**Comment by RubenVerborgh** [comment]
Hi @martines3000, we can't because this method name is prescribed by http://rdf.js.org/stream-spec/

Perhaps monkey patching (there exist npm tools for this) might help you out.

**Comment by martines3000** [comment]
Hi, thanks for the quick reply.

I am already doing that, but it is quite tedious as I need to patch multiple libraries and rebuild a some of them.

Is there maybe a way to raise the issue to the specification writers, as I think it is also not a good practice to use “reserved” keywords like that as method names?

**Comment by RubenVerborgh** [comment]
Indeed; the spec repository is part of this GitHub organization, would be good to raise it there.
