### ISSUE TITLE
Circular imports

### ISSUE THREAD

**Issue by martines3000** [rdfjs/N3.js#381]
Hi. I found that 2 files have circular imports.

N3DataFactory.js and N3Utils.js

https://github.com/rdfjs/N3.js/blob/51a41564467252278f4b8b5998453ad88f607ced/src/N3DataFactory.js#L5

https://github.com/rdfjs/N3.js/blob/51a41564467252278f4b8b5998453ad88f607ced/src/N3Util.js#L3

**Comment by RubenVerborgh** [comment]
Is there a situation where this leads to problems? This is compiled away.

**Comment by martines3000** [comment]
Its compiled away in the browser version (`n3.min.js`), but the cyclic import is still there in the `lib` folder on NPM.

Its causing some errors and I also get a warning from rollup about circular dependencies.

**Comment by RubenVerborgh** [comment]
Ok, let me look into it!

**Comment by martines3000** [comment]
Thank you, much appreciated. 💯
