### ISSUE TITLE
CURIE like s:a/b/c not supported

### ISSUE THREAD

**Issue by sahuguet** [rdfjs/N3.js#384]
The N3.js lexer does not recognize CURIEs containing a slash `/`, e.g. `s:a/1`.

The CURIE spec does not prohibit this kind of syntax, as far as I can tell.

Am I missing something?

**Comment by RubenVerborgh** [comment]
Hi @sahuguet, Turtle parsers aren't governed by the CURIE spec but the [Turtle spec](https://www.w3.org/TR/turtle/), which doesn't allow them.
