### ISSUE TITLE
Support for set operations on graphs/datasets in the N3Store

### ISSUE THREAD

**Issue by edmondchuc** [rdfjs/N3.js#390]
Hi, I was wondering if it's within the scope of N3.js to support set operations on graphs or datasets within the N3Store?

If I am able to contribute an implementation, would you accept it? Or would an extension like this fall outside the scope of N3.js?

**Comment by jeswr** [comment]
What kind of set operations do you have in mind? 

If you are referring to methods such as [#contains](https://rdf.js.org/dataset-spec/#methods-0) from the RDF/JS dataset spec; then there is this PR that you're welcome to take over https://github.com/rdfjs/N3.js/pull/288. I think it would be ok to leave `#toCanonical` unimplemented as that would likely require introducing https://github.com/iherman/rdfjs-c14n as a dependency, or to require a `canonicalize` function in the `Store` constructor for that method to work. `#toString` can just use the [`Writer#quadsToString`](https://github.com/rdfjs/N3.js/blob/a07e8728c12b78de19502e7f7cbac86e08aa5ee2/src/N3Writer.js#L132-L135) function.

**Comment by edmondchuc** [comment]
I'm interested in the mathematical set operations from Python's RDFLib as described in [Set Operations on RDFLib Graphs](https://rdflib.readthedocs.io/en/stable/intro_to_graphs.html#set-operations-on-rdflib-graphs).

We can probably turn the N3Store or its graphs into set-like objects by implementing these [set methods](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set#set_composition).

Though I'm not sure how well these set methods translate to a store, which is effectively an RDF Dataset, and N3 doesn't really have the notion of graphs.

Would be happy to hear your thoughts on this.

**Comment by edmondchuc** [comment]
Ok thanks, sorry I'm not too familiar with the RDF/JS spec, and didn't realise the intersect and difference methods are already specified there. Your PR looks exactly like what I was after! I'll take a look at it when I can. Cheers.

**Comment by jeswr** [comment]
FWIW https://rdfjs.dev/ is a good point for jumping into more libraries with different layers of abstraction in the RDF/JS ecosystem
