### ISSUE TITLE
Why does `#every` return false on the empty store

### ISSUE THREAD

**Issue by jeswr** [rdfjs/N3.js#391]
As shown in the test here `#every` returns `false` when called on an empty store. There is a test enforcing this behavior at https://github.com/rdfjs/N3.js/blob/0ba9ec2e0e7d812f9e86985de3966583d228e189/test/N3Store-test.js#L92 This does not align with set semantics where `#every` would align with `forAll` and thus be vacuously `true` on the empty set.

It also goes against the RDF/JS Dataset definition of for `#every` https://rdf.js.org/dataset-spec/#dom-dataset-every; and so in order to complete https://github.com/rdfjs/N3.js/pull/288 we would need to alter this behavior and decide whether this change is (1) breaking or (2) a bug fix - despite the fact that there is a test enforcing the buggy behavior. @RubenVerborgh what do you think?

**Comment by RubenVerborgh** [comment]
Oops; let's treat as a bug fix. The test is wrong indeed.
